Jcn 358 avoid saving empty settings
janis-commerce/client-settings pull request #12
Opened 2022-02-22 22:27 UTC by AngeloSalvador7

Tarea: https://fizzmod.atlassian.net/browse/JCN-357
Subtarea: https://fizzmod.atlassian.net/browse/JCN-358

Dato a tener en cuenta:

En el archivo `lib/put-setting-api.js`, específicamente en la línea `80`
Valido el valor así
`this.defaultSettings[settingName].saveEmptyValue === false`
en vez de 
`!this.defaultSettings[settingName].saveEmptyValue`
 porque según mi análisis pueden haber schemas en los cuales no esté setteada esa propiedad.
 
 Quedo atento a comentarios.

2022-02-24 14:28 UTC, Nataniel4 approved these changes
Aprobado 😌

2022-03-03 04:07 UTC, manuelvilche requested changes

2022-03-03 04:07 UTC, manuelvilche commented on lib/put-setting-api.js
> +		if(!Object.keys(dataToSave).length)
@AngeloSalvador7 Esto que planteabas que no pedia el ticket no esta OK 🙃 haciendo esto, no hay forma de poder borrar lo que estaba en la base! mismo haciendo unas pruebas podíamos habernos a darnos cuenta que esta mal esta linea! siempre siempre debe actualizar!

2022-03-03 04:07 UTC, manuelvilche commented on README.md
> +Important:
temamosle un poco más de pilas a este important! algún icono, alguna etiqueda de html

2022-03-03 04:07 UTC, manuelvilche commented on README.md
> +If the setting property `saveEmptyValue` is set to `false`, any of the following values `null - '' - 0 - {} - []` will not be saved.
Agregaria también que en caso de no enviarlo, el default es `true`!

2022-03-10 20:54 UTC, merged