JCN 320 cambiar guardado settings
janis-commerce/client-settings pull request #5
Opened 2021-03-18 12:40 UTC by gastonpereyra

**LINK AL TICKET**
https://fizzmod.atlassian.net/browse/JCN-320

**DESCRIPCIÓN DEL REQUERIMIENTO**

* Actualizar y mejorar el package https://github.com/janis-commerce/client-settings
* Client-Settings debe estar actualizado
* No debe usar un modelo de clients-settings
* Debe usar el modelo de Clientes del servicio
* Debe guardar las settings en cada cliente en la colección de clientes
* Debe buscar esas settings donde corresponde
* Actualizar Readme

**DESCRIPCIÓN DE LA SOLUCIÓN**
Se desarrollaron los requerimientos solicitado. 
Se agrego un Cache con TTL para guardar temporalmente los settings

2021-03-18 14:01 UTC, KarenEchavarria commented on CHANGELOG.md
> +- Client-Settings APIs and Client-Settings class uses Service Client's Model
Puede quedar mas claro el cambio con '**Now** Client-Settings...'

2021-03-18 14:54 UTC, KarenEchavarria commented on lib/client-settings.js
> +const cacheTime = 60 * 60 * 12; // Half Day
Aquí me parece que hay un magic number, si bien lo aclaras en el comentario, es medio confuso a qué se refiere. Para mi la variable podría llamarse algo como `halfDayInSeconds` y así queda más claro la operación y luego cuando se llama en el getter da mas información del tiempo cache

2021-03-18 15:10 UTC, KarenEchavarria commented on lib/get-setting-api.js
>  		Object.entries(defaultSettings).forEach(([settingName, setting]) => {
En el metodo `getForClient` de la clase `ClientSettings` haces un procesamiento similar usando un reduce en lugar de un objeto + forEach, para que quede un poco mas uniforme, elije la forma que mas te guste y úsala en ambos :)

2021-03-18 15:20 UTC, KarenEchavarria commented on lib/put-setting-api.js
> +			throw new Error(`Invalid Model Client. Must be in ${clientModelPath}.`);
El mensaje puede ser un poco confuso ya que no es que se este validando el modelo como tal, sino que cuando lo fue a buscar no estaba en el path que debería. Capaz seria mas claro algo como 'Model Client not found. Must be...'

2021-03-18 15:48 UTC, KarenEchavarria commented on tests/get-setting-api.js
> +			description: 'Should reject if the definition file its not found',
le falta un apostrofe al it's

2021-03-18 15:50 UTC, KarenEchavarria commented on tests/get-setting-api.js
> +			description: 'Should reject if the entity not found in the definition file',
...the entity **is** not found...

2021-03-18 15:51 UTC, KarenEchavarria commented on tests/put-setting-api.js
> +			description: 'Should rejects if the definition file its not found',
aquí también falta el apostrofe en it's

2021-03-18 15:57 UTC, KarenEchavarria commented on README.md
> +It also provides you with a class to easily get the settings value per client, with a fallback in the default values you have previously defined. You have many other tools to help you, like two APIs
En lugar de _and_ puedes poner **also**. El link podria ser al paquete de npm, asi queda como lo demas. Te quedo client-creat**E**r :)

2021-03-18 21:26 UTC, KarenEchavarria approved these changes
Aprobado por mi parte, me pareció excelente que tomaras la iniciativa de agregar le método para settear el cache!

2021-03-23 13:48 UTC, manuelvilche requested changes

2021-03-23 14:14 UTC, gastonpereyra commented on docs/view-schemas/setting/edit.yml
> -source:
Sin el source y el target, funciona sin errores.
Lo tengo hecho en el DOM.

El Schema
![image](https://user-images.githubusercontent.com/39351850/112160270-c339d780-8bc8-11eb-9a96-3cb737b3a105.png)

La vista
![image](https://user-images.githubusercontent.com/39351850/112160340-d351b700-8bc8-11eb-9789-c2019c3d824f.png)

Pero agrego con algún comentario por las dudas

2021-03-23 14:48 UTC, manuelvilche requested changes

2021-03-23 14:48 UTC, manuelvilche commented on docs/view-schemas/setting/edit.yml
> -source:
Toda la razon! no hace falta sorry! 👼  nunca vamos a poder tener un mainForm, por que no tenemos un `Id` me olvide de esa parte! voletealo de nuevo!

2021-03-23 15:00 UTC, manuelvilche approved these changes

2021-03-23 15:00 UTC, merged